name: Stocks hourly

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - name: Call Stocks endpoint
        run: |
          curl -fsS "$DEPLOY_URL/api/stocks" || exit 1
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
