name: WTI 6-hourly

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  call:
    runs-on: ubuntu-latest
    steps:
      - name: Call WTI endpoint
        run: |
          curl -fsS "$DEPLOY_URL/api/wti" || exit 1
        env:
          DEPLOY_URL: ${{ secrets.DEPLOY_URL }}
